import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import {
  BadRequestException,
  ConflictException,
  GatewayTimeoutException,
  Injectable,
  NotFoundException,
  PayloadTooLargeException,
  ServiceUnavailableException,
  UnprocessableEntityException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { directorySize } from './disk-usage.js';
import { CloneError, GitCloner } from './git-cloner.js';
import { Project } from './project.entity.js';

export interface CloningOptions {
  cloner: GitCloner;
  cloningAvailable: boolean;
  userStorageMaxBytes: number;
}

type RemovalHook = (userId: string, projectId: string) => Promise<void>;

@Injectable()
export class ProjectsService {
  private readonly beforeRemove: RemovalHook[] = [];

  constructor(
    @InjectRepository(Project) private readonly projects: Repository<Project>,
    private readonly root: string,
    private readonly cloning: CloningOptions,
  ) {}
  private readonly cloningNow = new Set<string>();
  /** Clones in progress by project id, so deleting the project can stop its clone. */
  private readonly cloneStops = new Map<string, () => void>();

  /** Others (the run registry) register to be asked before a project goes away, so a running agent stops first. */
  onBeforeRemove(hook: RemovalHook): void {
    this.beforeRemove.push(hook);
  }

  /** Ids are UUIDs generated by the database, so the path cannot leave the root. */
  directoryOf(userId: string, projectId: string): string {
    return path.join(this.root, userId, projectId);
  }

  async create(userId: string, name: string, cloneUrl?: string, signal?: AbortSignal): Promise<Project> {
    if (cloneUrl !== undefined)
      return this.createCloned(userId, name, cloneUrl, signal ?? new AbortController().signal);
    const project = await this.projects.save(this.projects.create({ userId, name, origin: 'empty' }));
    try {
      await mkdir(this.directoryOf(userId, project.id), { recursive: true });
    } catch (error) {
      await this.projects.delete({ id: project.id });
      throw error;
    }
    return project;
  }

  /** Clones first, then records the project, so a failed clone leaves nothing behind. One clone per user at a time. */
  private async createCloned(userId: string, name: string, cloneUrl: string, signal: AbortSignal): Promise<Project> {
    if (!this.cloning.cloningAvailable)
      throw new ServiceUnavailableException('Cloning is not available on this server.');
    const url = this.parseUrl(cloneUrl);
    if (this.cloningNow.has(userId)) throw new ConflictException('Another clone is still running. Wait until it ends.');
    this.cloningNow.add(userId);
    try {
      const left = this.cloning.userStorageMaxBytes - (await directorySize(path.join(this.root, userId)));
      if (left <= 0) throw new PayloadTooLargeException('Your storage is full. Delete a project to make room.');
      const project = await this.projects.save(this.projects.create({ userId, name, origin: url }));
      const own = new AbortController();
      this.cloneStops.set(project.id, () => own.abort());
      try {
        await this.cloning.cloner.clone(
          url,
          this.directoryOf(userId, project.id),
          AbortSignal.any([signal, own.signal]),
          {
            maxBytes: left,
          },
        );
        // Deleted while it was cloning: the folder must not outlive the project.
        if (own.signal.aborted) throw new NotFoundException('The project was deleted while it was cloned.');
      } catch (error) {
        await this.projects.delete({ id: project.id });
        await rm(this.directoryOf(userId, project.id), { recursive: true, force: true });
        throw this.cloneFailure(error);
      } finally {
        this.cloneStops.delete(project.id);
      }
      return project;
    } finally {
      this.cloningNow.delete(userId);
    }
  }

  private parseUrl(raw: string): string {
    try {
      return GitCloner.parseUrl(raw);
    } catch (error) {
      throw this.cloneFailure(error);
    }
  }

  private cloneFailure(error: unknown): unknown {
    if (!(error instanceof CloneError)) return error;
    switch (error.code) {
      case 'invalid_url':
        return new BadRequestException(error.message);
      case 'too_large':
        return new PayloadTooLargeException(error.message);
      case 'timeout':
        return new GatewayTimeoutException(error.message);
      case 'unavailable':
        return new ServiceUnavailableException(error.message);
      default:
        return new UnprocessableEntityException(error.message);
    }
  }

  list(userId: string): Promise<Project[]> {
    return this.projects.find({ where: { userId }, order: { createdAt: 'DESC' } });
  }

  async getOwned(userId: string, id: string): Promise<Project> {
    const project = await this.projects.findOneBy({ id, userId });
    if (!project) throw new NotFoundException('Project not found');
    return project;
  }

  async rename(userId: string, id: string, name: string): Promise<Project> {
    const project = await this.getOwned(userId, id);
    project.name = name;
    return this.projects.save(project);
  }

  async remove(userId: string, id: string): Promise<void> {
    await this.getOwned(userId, id);
    for (const hook of this.beforeRemove) await hook(userId, id);
    this.cloneStops.get(id)?.();
    await this.projects.delete({ id });
    await rm(this.directoryOf(userId, id), { recursive: true, force: true });
  }

  /** Removes all projects of the user, then whatever else is left in the user's folder. */
  async removeAll(userId: string): Promise<void> {
    for (const project of await this.list(userId)) await this.remove(userId, project.id);
    await rm(path.join(this.root, userId), { recursive: true, force: true });
  }
}
