import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Project } from './project.entity.js';

type RemovalHook = (userId: string, projectId: string) => Promise<void>;

@Injectable()
export class ProjectsService {
  private readonly beforeRemove: RemovalHook[] = [];

  constructor(
    @InjectRepository(Project) private readonly projects: Repository<Project>,
    private readonly root: string,
  ) {}

  /** Others (the run registry) register to be asked before a project goes away, so a running agent stops first. */
  onBeforeRemove(hook: RemovalHook): void {
    this.beforeRemove.push(hook);
  }

  /** Ids are UUIDs generated by the database, so the path cannot leave the root. */
  directoryOf(userId: string, projectId: string): string {
    return path.join(this.root, userId, projectId);
  }

  async create(userId: string, name: string): Promise<Project> {
    const project = await this.projects.save(this.projects.create({ userId, name, origin: 'empty' }));
    try {
      await mkdir(this.directoryOf(userId, project.id), { recursive: true });
    } catch (error) {
      await this.projects.delete({ id: project.id });
      throw error;
    }
    return project;
  }

  list(userId: string): Promise<Project[]> {
    return this.projects.find({ where: { userId }, order: { createdAt: 'DESC' } });
  }

  async getOwned(userId: string, id: string): Promise<Project> {
    const project = await this.projects.findOneBy({ id, userId });
    if (!project) throw new NotFoundException('Project not found');
    return project;
  }

  async rename(userId: string, id: string, name: string): Promise<Project> {
    const project = await this.getOwned(userId, id);
    project.name = name;
    return this.projects.save(project);
  }

  async remove(userId: string, id: string): Promise<void> {
    await this.getOwned(userId, id);
    for (const hook of this.beforeRemove) await hook(userId, id);
    await this.projects.delete({ id });
    await rm(this.directoryOf(userId, id), { recursive: true, force: true });
  }
}
